name: Publish Package to npm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Get Latest Version
        run: pnpm getLatestVersion

      - name: Configure Git
        run: |
          git config --global user.email "alghi344@gmail.com"
          git config --global user.name "argf013"

      - name: Publish to npm
        run: |
          npm publish --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
